/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountServiceConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountServiceConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plansConfig" type="{http://www.progress.com/cs/1.0/tenant-config}plansConfig" minOccurs="0"/>
 *         &lt;element name="accountLimits" type="{http://www.progress.com/cs/1.0/tenant-config}accountLimits" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountServiceConfig", propOrder = {
    "plansConfig",
    "accountLimits"
})
public class AccountServiceConfig {

    protected PlansConfig plansConfig;
    protected AccountLimits accountLimits;

    /**
     * Gets the value of the plansConfig property.
     * 
     * @return
     *     possible object is
     *     {@link PlansConfig }
     *     
     */
    public PlansConfig getPlansConfig() {
        return plansConfig;
    }

    /**
     * Sets the value of the plansConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlansConfig }
     *     
     */
    public void setPlansConfig(PlansConfig value) {
        this.plansConfig = value;
    }

    /**
     * Gets the value of the accountLimits property.
     * 
     * @return
     *     possible object is
     *     {@link AccountLimits }
     *     
     */
    public AccountLimits getAccountLimits() {
        return accountLimits;
    }

    /**
     * Sets the value of the accountLimits property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountLimits }
     *     
     */
    public void setAccountLimits(AccountLimits value) {
        this.accountLimits = value;
    }

}
