/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountNotificationApi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountNotificationApi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="endPointURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="maxRetryLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="retryTimeInterval" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountNotificationApi", propOrder = {
    "endPointURL",
    "maxRetryLimit",
    "retryTimeInterval"
})
public class AccountNotificationApi {

    @XmlElement(required = true)
    protected String endPointURL;
    protected int maxRetryLimit;
    protected long retryTimeInterval;

    /**
     * Gets the value of the endPointURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndPointURL() {
        return endPointURL;
    }

    /**
     * Sets the value of the endPointURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPointURL(String value) {
        this.endPointURL = value;
    }

    /**
     * Gets the value of the maxRetryLimit property.
     * 
     */
    public int getMaxRetryLimit() {
        return maxRetryLimit;
    }

    /**
     * Sets the value of the maxRetryLimit property.
     * 
     */
    public void setMaxRetryLimit(int value) {
        this.maxRetryLimit = value;
    }

    /**
     * Gets the value of the retryTimeInterval property.
     * 
     */
    public long getRetryTimeInterval() {
        return retryTimeInterval;
    }

    /**
     * Sets the value of the retryTimeInterval property.
     * 
     */
    public void setRetryTimeInterval(long value) {
        this.retryTimeInterval = value;
    }

}
