/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addOn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addOn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billingName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiLimit" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addOn", propOrder = {
    "billingName",
    "uiUnit",
    "uiName",
    "uiLimit"
})
public class AddOn {

    @XmlElement(required = true)
    protected String billingName;
    @XmlElement(required = true)
    protected String uiUnit;
    @XmlElement(required = true)
    protected String uiName;
    protected int uiLimit;

    /**
     * Gets the value of the billingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingName() {
        return billingName;
    }

    /**
     * Sets the value of the billingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingName(String value) {
        this.billingName = value;
    }

    /**
     * Gets the value of the uiUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiUnit() {
        return uiUnit;
    }

    /**
     * Sets the value of the uiUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiUnit(String value) {
        this.uiUnit = value;
    }

    /**
     * Gets the value of the uiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiName() {
        return uiName;
    }

    /**
     * Sets the value of the uiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiName(String value) {
        this.uiName = value;
    }

    /**
     * Gets the value of the uiLimit property.
     * 
     */
    public int getUiLimit() {
        return uiLimit;
    }

    /**
     * Sets the value of the uiLimit property.
     * 
     */
    public void setUiLimit(int value) {
        this.uiLimit = value;
    }

}
