/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for endPoints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="endPoints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="authConfig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="authType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="accountProvisionApi" type="{http://www.progress.com/cs/1.0/tenant-config}accountProvisionApi" minOccurs="0"/>
 *         &lt;element name="accountNotificationApi" type="{http://www.progress.com/cs/1.0/tenant-config}accountNotificationApi" minOccurs="0"/>
 *         &lt;element name="pConsoleCardConfig" type="{http://www.progress.com/cs/1.0/tenant-config}pConsoleCardConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "endPoints", propOrder = {
    "authConfig",
    "accountProvisionApi",
    "accountNotificationApi",
    "pConsoleCardConfig"
})
public class EndPoints {

    @XmlElement(required = true)
    protected EndPoints.AuthConfig authConfig;
    protected AccountProvisionApi accountProvisionApi;
    protected AccountNotificationApi accountNotificationApi;
    protected PConsoleCardConfig pConsoleCardConfig;

    /**
     * Gets the value of the authConfig property.
     * 
     * @return
     *     possible object is
     *     {@link EndPoints.AuthConfig }
     *     
     */
    public EndPoints.AuthConfig getAuthConfig() {
        return authConfig;
    }

    /**
     * Sets the value of the authConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPoints.AuthConfig }
     *     
     */
    public void setAuthConfig(EndPoints.AuthConfig value) {
        this.authConfig = value;
    }

    /**
     * Gets the value of the accountProvisionApi property.
     * 
     * @return
     *     possible object is
     *     {@link AccountProvisionApi }
     *     
     */
    public AccountProvisionApi getAccountProvisionApi() {
        return accountProvisionApi;
    }

    /**
     * Sets the value of the accountProvisionApi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountProvisionApi }
     *     
     */
    public void setAccountProvisionApi(AccountProvisionApi value) {
        this.accountProvisionApi = value;
    }

    /**
     * Gets the value of the accountNotificationApi property.
     * 
     * @return
     *     possible object is
     *     {@link AccountNotificationApi }
     *     
     */
    public AccountNotificationApi getAccountNotificationApi() {
        return accountNotificationApi;
    }

    /**
     * Sets the value of the accountNotificationApi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountNotificationApi }
     *     
     */
    public void setAccountNotificationApi(AccountNotificationApi value) {
        this.accountNotificationApi = value;
    }

    /**
     * Gets the value of the pConsoleCardConfig property.
     * 
     * @return
     *     possible object is
     *     {@link PConsoleCardConfig }
     *     
     */
    public PConsoleCardConfig getPConsoleCardConfig() {
        return pConsoleCardConfig;
    }

    /**
     * Sets the value of the pConsoleCardConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link PConsoleCardConfig }
     *     
     */
    public void setPConsoleCardConfig(PConsoleCardConfig value) {
        this.pConsoleCardConfig = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="authType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authType",
        "username",
        "password"
    })
    public static class AuthConfig {

        @XmlElement(required = true)
        protected String authType;
        @XmlElement(required = true)
        protected String username;
        @XmlElement(required = true)
        protected String password;

        /**
         * Gets the value of the authType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthType() {
            return authType;
        }

        /**
         * Sets the value of the authType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthType(String value) {
            this.authType = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

    }

}
