/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for meteringServiceConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="meteringServiceConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usageType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="usageTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="usageTypeUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="uploadToBillingSystem" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                 &lt;attribute name="mode" default="incremental">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="incremental"/>
 *                       &lt;enumeration value="absolute"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "meteringServiceConfig", propOrder = {
    "usageType"
})
public class MeteringServiceConfig {

    protected List<MeteringServiceConfig.UsageType> usageType;

    /**
     * Gets the value of the usageType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usageType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsageType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeteringServiceConfig.UsageType }
     * 
     * 
     */
    public List<MeteringServiceConfig.UsageType> getUsageType() {
        if (usageType == null) {
            usageType = new ArrayList<MeteringServiceConfig.UsageType>();
        }
        return this.usageType;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="usageTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="usageTypeUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="uploadToBillingSystem" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *       &lt;attribute name="mode" default="incremental">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="incremental"/>
     *             &lt;enumeration value="absolute"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "usageTypeName",
        "usageTypeUnit"
    })
    public static class UsageType {

        @XmlElement(required = true)
        protected String usageTypeName;
        @XmlElement(required = true)
        protected String usageTypeUnit;
        @XmlAttribute(name = "uploadToBillingSystem")
        protected Boolean uploadToBillingSystem;
        @XmlAttribute(name = "mode")
        protected String mode;

        /**
         * Gets the value of the usageTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsageTypeName() {
            return usageTypeName;
        }

        /**
         * Sets the value of the usageTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsageTypeName(String value) {
            this.usageTypeName = value;
        }

        /**
         * Gets the value of the usageTypeUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsageTypeUnit() {
            return usageTypeUnit;
        }

        /**
         * Sets the value of the usageTypeUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsageTypeUnit(String value) {
            this.usageTypeUnit = value;
        }

        /**
         * Gets the value of the uploadToBillingSystem property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isUploadToBillingSystem() {
            if (uploadToBillingSystem == null) {
                return true;
            } else {
                return uploadToBillingSystem;
            }
        }

        /**
         * Sets the value of the uploadToBillingSystem property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setUploadToBillingSystem(Boolean value) {
            this.uploadToBillingSystem = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            if (mode == null) {
                return "incremental";
            } else {
                return mode;
            }
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

    }

}
