/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notificationServiceConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="notificationServiceConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="notificationEndPointURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notificationTimeOut" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notificationServiceConfig", propOrder = {
    "notificationEndPointURL",
    "notificationTimeOut"
})
public class NotificationServiceConfig {

    @XmlElement(required = true)
    protected String notificationEndPointURL;
    @XmlElement(defaultValue = "60")
    protected int notificationTimeOut;

    /**
     * Gets the value of the notificationEndPointURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationEndPointURL() {
        return notificationEndPointURL;
    }

    /**
     * Sets the value of the notificationEndPointURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationEndPointURL(String value) {
        this.notificationEndPointURL = value;
    }

    /**
     * Gets the value of the notificationTimeOut property.
     * 
     */
    public int getNotificationTimeOut() {
        return notificationTimeOut;
    }

    /**
     * Sets the value of the notificationTimeOut property.
     * 
     */
    public void setNotificationTimeOut(int value) {
        this.notificationTimeOut = value;
    }

}
