/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.progress.cloudservices.common.tenant.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tenant_QNAME = new QName("http://www.progress.com/cs/1.0/tenant-config", "tenant");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.progress.cloudservices.common.tenant.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlansConfig }
     * 
     */
    public PlansConfig createPlansConfig() {
        return new PlansConfig();
    }

    /**
     * Create an instance of {@link PlansConfig.CorporatePlan }
     * 
     */
    public PlansConfig.CorporatePlan createPlansConfigCorporatePlan() {
        return new PlansConfig.CorporatePlan();
    }

    /**
     * Create an instance of {@link PlansConfig.CorporatePlan.PlanDetails }
     * 
     */
    public PlansConfig.CorporatePlan.PlanDetails createPlansConfigCorporatePlanPlanDetails() {
        return new PlansConfig.CorporatePlan.PlanDetails();
    }

    /**
     * Create an instance of {@link PlansConfig.NonPaidPlan }
     * 
     */
    public PlansConfig.NonPaidPlan createPlansConfigNonPaidPlan() {
        return new PlansConfig.NonPaidPlan();
    }

    /**
     * Create an instance of {@link MeteringServiceConfig }
     * 
     */
    public MeteringServiceConfig createMeteringServiceConfig() {
        return new MeteringServiceConfig();
    }

    /**
     * Create an instance of {@link EndPoints }
     * 
     */
    public EndPoints createEndPoints() {
        return new EndPoints();
    }

    /**
     * Create an instance of {@link AccountLimits }
     * 
     */
    public AccountLimits createAccountLimits() {
        return new AccountLimits();
    }

    /**
     * Create an instance of {@link PConsoleCardConfig }
     * 
     */
    public PConsoleCardConfig createPConsoleCardConfig() {
        return new PConsoleCardConfig();
    }

    /**
     * Create an instance of {@link TenantConfig }
     * 
     */
    public TenantConfig createTenantConfig() {
        return new TenantConfig();
    }

    /**
     * Create an instance of {@link NotificationServiceConfig }
     * 
     */
    public NotificationServiceConfig createNotificationServiceConfig() {
        return new NotificationServiceConfig();
    }

    /**
     * Create an instance of {@link KeyValuePairType }
     * 
     */
    public KeyValuePairType createKeyValuePairType() {
        return new KeyValuePairType();
    }

    /**
     * Create an instance of {@link AddOnsConfig }
     * 
     */
    public AddOnsConfig createAddOnsConfig() {
        return new AddOnsConfig();
    }

    /**
     * Create an instance of {@link AccountServiceConfig }
     * 
     */
    public AccountServiceConfig createAccountServiceConfig() {
        return new AccountServiceConfig();
    }

    /**
     * Create an instance of {@link AccountNotificationApi }
     * 
     */
    public AccountNotificationApi createAccountNotificationApi() {
        return new AccountNotificationApi();
    }

    /**
     * Create an instance of {@link AddOn }
     * 
     */
    public AddOn createAddOn() {
        return new AddOn();
    }

    /**
     * Create an instance of {@link TenantAdditionalPropsConfig }
     * 
     */
    public TenantAdditionalPropsConfig createTenantAdditionalPropsConfig() {
        return new TenantAdditionalPropsConfig();
    }

    /**
     * Create an instance of {@link MailServiceConfig }
     * 
     */
    public MailServiceConfig createMailServiceConfig() {
        return new MailServiceConfig();
    }

    /**
     * Create an instance of {@link DataSourceConfig }
     * 
     */
    public DataSourceConfig createDataSourceConfig() {
        return new DataSourceConfig();
    }

    /**
     * Create an instance of {@link AccountProvisionApi }
     * 
     */
    public AccountProvisionApi createAccountProvisionApi() {
        return new AccountProvisionApi();
    }

    /**
     * Create an instance of {@link DataSourceImage }
     * 
     */
    public DataSourceImage createDataSourceImage() {
        return new DataSourceImage();
    }

    /**
     * Create an instance of {@link DataSourcesConfig }
     * 
     */
    public DataSourcesConfig createDataSourcesConfig() {
        return new DataSourcesConfig();
    }

    /**
     * Create an instance of {@link UIServiceConfig }
     * 
     */
    public UIServiceConfig createUIServiceConfig() {
        return new UIServiceConfig();
    }

    /**
     * Create an instance of {@link PlansConfig.CorporatePlan.PlanDetails.Rates }
     * 
     */
    public PlansConfig.CorporatePlan.PlanDetails.Rates createPlansConfigCorporatePlanPlanDetailsRates() {
        return new PlansConfig.CorporatePlan.PlanDetails.Rates();
    }

    /**
     * Create an instance of {@link PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned }
     * 
     */
    public PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned createPlansConfigNonPaidPlanOtherTenantsToBeProvisioned() {
        return new PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned();
    }

    /**
     * Create an instance of {@link MeteringServiceConfig.UsageType }
     * 
     */
    public MeteringServiceConfig.UsageType createMeteringServiceConfigUsageType() {
        return new MeteringServiceConfig.UsageType();
    }

    /**
     * Create an instance of {@link EndPoints.AuthConfig }
     * 
     */
    public EndPoints.AuthConfig createEndPointsAuthConfig() {
        return new EndPoints.AuthConfig();
    }

    /**
     * Create an instance of {@link AccountLimits.AccountLimitsFields }
     * 
     */
    public AccountLimits.AccountLimitsFields createAccountLimitsAccountLimitsFields() {
        return new AccountLimits.AccountLimitsFields();
    }

    /**
     * Create an instance of {@link PConsoleCardConfig.UsageType }
     * 
     */
    public PConsoleCardConfig.UsageType createPConsoleCardConfigUsageType() {
        return new PConsoleCardConfig.UsageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TenantConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.progress.com/cs/1.0/tenant-config", name = "tenant")
    public JAXBElement<TenantConfig> createTenant(TenantConfig value) {
        return new JAXBElement<TenantConfig>(_Tenant_QNAME, TenantConfig.class, null, value);
    }

}
