/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.progress.com/cs/1.0/tenant-config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.progress.cloudservices.CommonTenantConfig;
