/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for plansConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="plansConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nonPaidPlan" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nonPaidPlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="billingPlanName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="otherTenantsToBeProvisioned" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tenantName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="propogateTobilling" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="corporatePlan" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="planNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="planDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="getInTouchURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="pricingText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="planDetails" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="contractPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                               &lt;element name="rates" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "plansConfig", propOrder = {
    "nonPaidPlan",
    "corporatePlan"
})
public class PlansConfig {

    protected List<PlansConfig.NonPaidPlan> nonPaidPlan;
    protected List<PlansConfig.CorporatePlan> corporatePlan;

    /**
     * Gets the value of the nonPaidPlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonPaidPlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonPaidPlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlansConfig.NonPaidPlan }
     * 
     * 
     */
    public List<PlansConfig.NonPaidPlan> getNonPaidPlan() {
        if (nonPaidPlan == null) {
            nonPaidPlan = new ArrayList<PlansConfig.NonPaidPlan>();
        }
        return this.nonPaidPlan;
    }

    /**
     * Gets the value of the corporatePlan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the corporatePlan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorporatePlan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlansConfig.CorporatePlan }
     * 
     * 
     */
    public List<PlansConfig.CorporatePlan> getCorporatePlan() {
        if (corporatePlan == null) {
            corporatePlan = new ArrayList<PlansConfig.CorporatePlan>();
        }
        return this.corporatePlan;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="planNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="planDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="getInTouchURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="pricingText" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="planDetails" maxOccurs="unbounded">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="contractPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                     &lt;element name="rates" maxOccurs="unbounded">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planNo",
        "planName",
        "planDescription",
        "getInTouchURL",
        "pricingText",
        "planDetails"
    })
    public static class CorporatePlan {

        protected String planNo;
        @XmlElement(required = true)
        protected String planName;
        @XmlElement(required = true)
        protected String planDescription;
        protected String getInTouchURL;
        protected String pricingText;
        protected List<PlansConfig.CorporatePlan.PlanDetails> planDetails;

        /**
         * Gets the value of the planNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanNo() {
            return planNo;
        }

        /**
         * Sets the value of the planNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanNo(String value) {
            this.planNo = value;
        }

        /**
         * Gets the value of the planName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanName() {
            return planName;
        }

        /**
         * Sets the value of the planName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanName(String value) {
            this.planName = value;
        }

        /**
         * Gets the value of the planDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanDescription() {
            return planDescription;
        }

        /**
         * Sets the value of the planDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanDescription(String value) {
            this.planDescription = value;
        }

        /**
         * Gets the value of the getInTouchURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGetInTouchURL() {
            return getInTouchURL;
        }

        /**
         * Sets the value of the getInTouchURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGetInTouchURL(String value) {
            this.getInTouchURL = value;
        }

        /**
         * Gets the value of the pricingText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPricingText() {
            return pricingText;
        }

        /**
         * Sets the value of the pricingText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPricingText(String value) {
            this.pricingText = value;
        }

        /**
         * Gets the value of the planDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the planDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlanDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlansConfig.CorporatePlan.PlanDetails }
         * 
         * 
         */
        public List<PlansConfig.CorporatePlan.PlanDetails> getPlanDetails() {
            if (planDetails == null) {
                planDetails = new ArrayList<PlansConfig.CorporatePlan.PlanDetails>();
            }
            return this.planDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contractPeriod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="rates" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contractPeriod",
            "rates"
        })
        public static class PlanDetails {

            @XmlElement(required = true)
            protected String contractPeriod;
            @XmlElement(required = true)
            protected List<PlansConfig.CorporatePlan.PlanDetails.Rates> rates;

            /**
             * Gets the value of the contractPeriod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContractPeriod() {
                return contractPeriod;
            }

            /**
             * Sets the value of the contractPeriod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContractPeriod(String value) {
                this.contractPeriod = value;
            }

            /**
             * Gets the value of the rates property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the rates property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRates().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PlansConfig.CorporatePlan.PlanDetails.Rates }
             * 
             * 
             */
            public List<PlansConfig.CorporatePlan.PlanDetails.Rates> getRates() {
                if (rates == null) {
                    rates = new ArrayList<PlansConfig.CorporatePlan.PlanDetails.Rates>();
                }
                return this.rates;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "currency",
                "price"
            })
            public static class Rates {

                @XmlElement(required = true)
                protected String currency;
                @XmlElement(required = true)
                protected String price;

                /**
                 * Gets the value of the currency property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurrency() {
                    return currency;
                }

                /**
                 * Sets the value of the currency property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurrency(String value) {
                    this.currency = value;
                }

                /**
                 * Gets the value of the price property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPrice() {
                    return price;
                }

                /**
                 * Sets the value of the price property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPrice(String value) {
                    this.price = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nonPaidPlanName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="billingPlanName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="otherTenantsToBeProvisioned" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tenantName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="propogateTobilling" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nonPaidPlanName",
        "billingPlanName",
        "otherTenantsToBeProvisioned"
    })
    public static class NonPaidPlan {

        @XmlElement(required = true)
        protected String nonPaidPlanName;
        protected String billingPlanName;
        protected PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned otherTenantsToBeProvisioned;
        @XmlAttribute(name = "propogateTobilling")
        protected Boolean propogateTobilling;

        /**
         * Gets the value of the nonPaidPlanName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonPaidPlanName() {
            return nonPaidPlanName;
        }

        /**
         * Sets the value of the nonPaidPlanName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonPaidPlanName(String value) {
            this.nonPaidPlanName = value;
        }

        /**
         * Gets the value of the billingPlanName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillingPlanName() {
            return billingPlanName;
        }

        /**
         * Sets the value of the billingPlanName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillingPlanName(String value) {
            this.billingPlanName = value;
        }

        /**
         * Gets the value of the otherTenantsToBeProvisioned property.
         * 
         * @return
         *     possible object is
         *     {@link PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned }
         *     
         */
        public PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned getOtherTenantsToBeProvisioned() {
            return otherTenantsToBeProvisioned;
        }

        /**
         * Sets the value of the otherTenantsToBeProvisioned property.
         * 
         * @param value
         *     allowed object is
         *     {@link PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned }
         *     
         */
        public void setOtherTenantsToBeProvisioned(PlansConfig.NonPaidPlan.OtherTenantsToBeProvisioned value) {
            this.otherTenantsToBeProvisioned = value;
        }

        /**
         * Gets the value of the propogateTobilling property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPropogateTobilling() {
            if (propogateTobilling == null) {
                return false;
            } else {
                return propogateTobilling;
            }
        }

        /**
         * Sets the value of the propogateTobilling property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPropogateTobilling(Boolean value) {
            this.propogateTobilling = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tenantName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tenantName"
        })
        public static class OtherTenantsToBeProvisioned {

            @XmlElement(required = true)
            protected List<String> tenantName;

            /**
             * Gets the value of the tenantName property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tenantName property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTenantName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTenantName() {
                if (tenantName == null) {
                    tenantName = new ArrayList<String>();
                }
                return this.tenantName;
            }

        }

    }

}
