/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.10 at 09:51:00 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tenantConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tenantConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tenantName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tenantBaseURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tenantLogoURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tenantOfficialName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="atc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tenantAdditionalProps" type="{http://www.progress.com/cs/1.0/tenant-config}tenantAdditionalPropsConfig" minOccurs="0"/>
 *         &lt;element name="tenantCorporateUrl" type="{http://www.progress.com/cs/1.0/tenant-config}tenantAccountUrl" minOccurs="0"/>
 *         &lt;element name="tenantPartnerUrl" type="{http://www.progress.com/cs/1.0/tenant-config}tenantAccountUrl" minOccurs="0"/>
 *         &lt;element name="accountService" type="{http://www.progress.com/cs/1.0/tenant-config}accountServiceConfig" minOccurs="0"/>
 *         &lt;element name="mailService" type="{http://www.progress.com/cs/1.0/tenant-config}mailServiceConfig" minOccurs="0"/>
 *         &lt;element name="meterService" type="{http://www.progress.com/cs/1.0/tenant-config}meteringServiceConfig" minOccurs="0"/>
 *         &lt;element name="notificationService" type="{http://www.progress.com/cs/1.0/tenant-config}notificationServiceConfig" minOccurs="0"/>
 *         &lt;element name="uiService" type="{http://www.progress.com/cs/1.0/tenant-config}UIServiceConfig" minOccurs="0"/>
 *         &lt;element name="addOns" type="{http://www.progress.com/cs/1.0/tenant-config}addOnsConfig" minOccurs="0"/>
 *         &lt;element name="endPoints" type="{http://www.progress.com/cs/1.0/tenant-config}endPoints" minOccurs="0"/>
 *         &lt;element name="dataSources" type="{http://www.progress.com/cs/1.0/tenant-config}dataSourcesConfig" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tenantConfig", propOrder = {
    "tenantName",
    "tenantBaseURL",
    "tenantLogoURL",
    "tenantOfficialName",
    "atc",
    "tenantAdditionalProps",
    "tenantCorporateUrl",
    "tenantPartnerUrl",
    "accountService",
    "mailService",
    "meterService",
    "notificationService",
    "uiService",
    "addOns",
    "endPoints",
    "dataSources"
})

public class TenantConfig {

    @XmlElement(required = true)
    protected String tenantName;
    @XmlElement(required = true)
    protected String tenantBaseURL;
    protected String tenantLogoURL;
    protected String tenantOfficialName;
    protected String atc;
    protected TenantAdditionalPropsConfig tenantAdditionalProps;
    protected TenantAccountUrl tenantCorporateUrl;
    protected TenantAccountUrl tenantPartnerUrl;
    protected AccountServiceConfig accountService;
    protected MailServiceConfig mailService;
    protected MeteringServiceConfig meterService;
    protected NotificationServiceConfig notificationService;
    protected UIServiceConfig uiService;
    protected AddOnsConfig addOns;
    protected EndPoints endPoints;
    protected DataSourcesConfig dataSources;

    /**
     * Gets the value of the tenantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantName() {
        return tenantName;
    }

    /**
     * Sets the value of the tenantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantName(String value) {
        this.tenantName = value;
    }

    /**
     * Gets the value of the tenantBaseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantBaseURL() {
        return tenantBaseURL;
    }

    /**
     * Sets the value of the tenantBaseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantBaseURL(String value) {
        this.tenantBaseURL = value;
    }

    /**
     * Gets the value of the tenantLogoURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantLogoURL() {
        return tenantLogoURL;
    }

    /**
     * Sets the value of the tenantLogoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantLogoURL(String value) {
        this.tenantLogoURL = value;
    }

    /**
     * Gets the value of the tenantOfficialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantOfficialName() {
        return tenantOfficialName;
    }

    /**
     * Sets the value of the tenantOfficialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantOfficialName(String value) {
        this.tenantOfficialName = value;
    }

    /**
     * Gets the value of the atc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtc() {
        return atc;
    }

    /**
     * Sets the value of the atc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtc(String value) {
        this.atc = value;
    }

    /**
     * Gets the value of the tenantAdditionalProps property.
     * 
     * @return
     *     possible object is
     *     {@link TenantAdditionalPropsConfig }
     *     
     */
    public TenantAdditionalPropsConfig getTenantAdditionalProps() {
        return tenantAdditionalProps;
    }

    /**
     * Sets the value of the tenantAdditionalProps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenantAdditionalPropsConfig }
     *     
     */
    public void setTenantAdditionalProps(TenantAdditionalPropsConfig value) {
        this.tenantAdditionalProps = value;
    }

    /**
     * Gets the value of the tenantCorporateUrl property.
     * 
     * @return
     *     possible object is
     *     {@link TenantAccountUrl }
     *     
     */
    public TenantAccountUrl getTenantCorporateUrl() {
        return tenantCorporateUrl;
    }

    /**
     * Sets the value of the tenantCorporateUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenantAccountUrl }
     *     
     */
    public void setTenantCorporateUrl(TenantAccountUrl value) {
        this.tenantCorporateUrl = value;
    }

    /**
     * Gets the value of the tenantPartnerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link TenantAccountUrl }
     *     
     */
    public TenantAccountUrl getTenantPartnerUrl() {
        return tenantPartnerUrl;
    }

    /**
     * Sets the value of the tenantPartnerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenantAccountUrl }
     *     
     */
    public void setTenantPartnerUrl(TenantAccountUrl value) {
        this.tenantPartnerUrl = value;
    }

    /**
     * Gets the value of the accountService property.
     * 
     * @return
     *     possible object is
     *     {@link AccountServiceConfig }
     *     
     */
    public AccountServiceConfig getAccountService() {
        return accountService;
    }

    /**
     * Sets the value of the accountService property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountServiceConfig }
     *     
     */
    public void setAccountService(AccountServiceConfig value) {
        this.accountService = value;
    }

    /**
     * Gets the value of the mailService property.
     * 
     * @return
     *     possible object is
     *     {@link MailServiceConfig }
     *     
     */
    public MailServiceConfig getMailService() {
        return mailService;
    }

    /**
     * Sets the value of the mailService property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailServiceConfig }
     *     
     */
    public void setMailService(MailServiceConfig value) {
        this.mailService = value;
    }

    /**
     * Gets the value of the meterService property.
     * 
     * @return
     *     possible object is
     *     {@link MeteringServiceConfig }
     *     
     */
    public MeteringServiceConfig getMeterService() {
        return meterService;
    }

    /**
     * Sets the value of the meterService property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeteringServiceConfig }
     *     
     */
    public void setMeterService(MeteringServiceConfig value) {
        this.meterService = value;
    }

    /**
     * Gets the value of the notificationService property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationServiceConfig }
     *     
     */
    public NotificationServiceConfig getNotificationService() {
        return notificationService;
    }

    /**
     * Sets the value of the notificationService property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationServiceConfig }
     *     
     */
    public void setNotificationService(NotificationServiceConfig value) {
        this.notificationService = value;
    }

    /**
     * Gets the value of the uiService property.
     * 
     * @return
     *     possible object is
     *     {@link UIServiceConfig }
     *     
     */
    public UIServiceConfig getUiService() {
        return uiService;
    }

    /**
     * Sets the value of the uiService property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIServiceConfig }
     *     
     */
    public void setUiService(UIServiceConfig value) {
        this.uiService = value;
    }

    /**
     * Gets the value of the addOns property.
     * 
     * @return
     *     possible object is
     *     {@link AddOnsConfig }
     *     
     */
    public AddOnsConfig getAddOns() {
        return addOns;
    }

    /**
     * Sets the value of the addOns property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddOnsConfig }
     *     
     */
    public void setAddOns(AddOnsConfig value) {
        this.addOns = value;
    }

    /**
     * Gets the value of the endPoints property.
     * 
     * @return
     *     possible object is
     *     {@link EndPoints }
     *     
     */
    public EndPoints getEndPoints() {
        return endPoints;
    }

    /**
     * Sets the value of the endPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndPoints }
     *     
     */
    public void setEndPoints(EndPoints value) {
        this.endPoints = value;
    }

    /**
     * Gets the value of the dataSources property.
     * 
     * @return
     *     possible object is
     *     {@link DataSourcesConfig }
     *     
     */
    public DataSourcesConfig getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSourcesConfig }
     *     
     */
    public void setDataSources(DataSourcesConfig value) {
        this.dataSources = value;
    }

}
