/*******************************************************************************
 * Copyright © 2014 Progress Software Corporation.  All Rights Reserved.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.03 at 03:03:22 PM IST 
//


package com.progress.cloudservices.CommonTenantConfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIServiceConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIServiceConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tenantRedirectURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tenantHelpURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tosURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tenantSessionExtensionURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="uiProp" type="{http://www.progress.com/cs/1.0/tenant-config}keyValuePairType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIServiceConfig", propOrder = {
    "tenantRedirectURL",
    "tenantHelpURL",
    "tosURL",
    "tenantSessionExtensionURL",
    "uiProp"
})
public class UIServiceConfig {

    @XmlElement(required = true)
    protected String tenantRedirectURL;
    protected String tenantHelpURL;
    protected String tosURL;
    @XmlElement(required = true)
    protected String tenantSessionExtensionURL;
    protected List<KeyValuePairType> uiProp;

    /**
     * Gets the value of the tenantRedirectURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantRedirectURL() {
        return tenantRedirectURL;
    }

    /**
     * Sets the value of the tenantRedirectURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantRedirectURL(String value) {
        this.tenantRedirectURL = value;
    }

    /**
     * Gets the value of the tenantHelpURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantHelpURL() {
        return tenantHelpURL;
    }

    /**
     * Sets the value of the tenantHelpURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantHelpURL(String value) {
        this.tenantHelpURL = value;
    }

    /**
     * Gets the value of the tosURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTosURL() {
        return tosURL;
    }

    /**
     * Sets the value of the tosURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTosURL(String value) {
        this.tosURL = value;
    }

    /**
     * Gets the value of the tenantSessionExtensionURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenantSessionExtensionURL() {
        return tenantSessionExtensionURL;
    }

    /**
     * Sets the value of the tenantSessionExtensionURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenantSessionExtensionURL(String value) {
        this.tenantSessionExtensionURL = value;
    }

    /**
     * Gets the value of the uiProp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uiProp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUiProp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePairType }
     * 
     * 
     */
    public List<KeyValuePairType> getUiProp() {
        if (uiProp == null) {
            uiProp = new ArrayList<KeyValuePairType>();
        }
        return this.uiProp;
    }

}
